spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: kafka-pattern
    producer:
      bootstrap-servers: localhost:5052
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:5052
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:5052
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:5052
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer